language: node_js
dist: trusty
node_js:
  - v8
  - v9
script:
  - npm run check
  - npm run test
after_script:
  - npx -p coveralls -- 'cat ./coverage/lcov.info | coveralls'
  - npx -p codecov -- 'cat ./coverage/lcov.info | codecov'
