language: node_js
dist: trusty
node_js:
  - v8
  - v9
  - v10
before_script:
  npm i -g npm@latest coveralls codecov
script:
  - npm cit --quiet
after_success:
  - 'cat ./coverage/lcov.info | coveralls'
  - 'cat ./coverage/lcov.info | codecov'
